/*
 * This header file is automatically generated by the Python project
 * The JSON config file named [conf.json] by default is converted to a
 * .h (this file) and a .cpp, where the cpp file contains a string literal
 * that contains an escaped version of the JSON that can be read by the c++
 * JSON library in Arduino sketch projects. This way we can be sure all the
 * sketch and Python projects share exactly the same configuration.
*/

#ifndef ACTIVITY_JSON_CONF_H_
#define ACTIVITY_JSON_CONF_H_

extern const char json_conf[];
extern const int json_conf_len;

#endif //ACTIVITY_JSON_CONF_H_
